Repository NativeScript/docs, pull requests merged in 2019-10, with the labels that each got.

#1782 docs: add a little more details on where else to contribute in README.md
  README.md
Labels: cla: yes

#1791 docs: change link to Karma docs to point to latest edition
  docs/tooling/testing/testing.md
Labels: cla: yes

#1794 Several minor fixes in the navigation articles
  docs/core-concepts/angular-navigation.md
  docs/core-concepts/navigation.md
Labels: cla: yes

#1797 refactor(app-templates): update wording to note that we've got a single repo for all templates
  docs/app-templates/app-templates.md
Labels: cla: yes

#1799 refactor(vscode-extension): add missing characters
  docs/tooling/visual-studio-code-extension.md
Labels: cla: yes

#1798 This PR removes the ToC at the beginning of the [get-support](https://docs.nativescript.org/get-support) article. The ToC in all articles is now on the right by design.
  docs/get-support.md
Labels: cla: yes

#1801 docs: qualifiers article update
  docs/ui/supporting-multiple-screens.md
Labels: cla: yes, docs, hacktoberfest

#1804 docs: remove random word
  docs/plugins/building-plugins.md
Labels: cla: yes

#1802 docs: update lazy loading article
  docs/performance-optimizations/lazy-loading.md
Labels: docs, hacktoberfest

#1805 docs: update README.md
  README.md
Labels: cla: yes

#1806 docs: removing the enterprise auth section
  docs/sidekick/user-guide/create-app/create-app-from-template.md
Labels: cla: yes

#1809 refactor: remove extraneous bullet
  docs/core-concepts/modules.md
Labels: cla: yes

#1816 docs: update contributors list
  README.md
Labels: cla: yes

#1813 Removed --bundle flag
  docs/performance-optimizations/startup-times.md
Labels: cla: yes

#1811 Improve docs
  docs/cookbook/tab-view-ng.md
  docs/core-concepts/accessing-native-apis-with-javascript.md
  docs/core-concepts/angular-data-binding.md
  docs/core-concepts/angular-navigation.md
  docs/core-concepts/data-binding.md
  docs/core-concepts/error-handling.md
  docs/core-concepts/memory-management.md
  docs/core-concepts/plugins.md
  docs/core-concepts/properties.md
  docs/core-concepts/utils.md
  docs/plugins/Android-Plugins-Infrastructure.md
  docs/plugins/implementing-core-theme.md
  docs/plugins/ui-plugin-custom.md
  docs/sidekick/user-guide/enterprise-auth/openid.md
  docs/sidekick/user-guide/enterprise-auth/saml.md
  docs/tooling/angular-cli.md
  docs/tooling/debugging/chrome-devtools.md
  docs/tooling/testing/end-to-end-testing/continuous-integration.md
  docs/tooling/testing/end-to-end-testing/customization.md
  docs/tooling/testing/end-to-end-testing/getting-started.md
Labels: cla: yes

#1825 fix: minor article updates
  docs/tooling/publishing/publishing-ios-apps.md
Labels: cla: yes

#1822 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#1824 Update README.md
  README.md
Labels: cla: yes

#1835 chore: fix missing slugs
  build/_config_angular.yml
  docs/ui/ng-components/ng-AutoCompleteTextView/overview.md
  docs/ui/ng-components/ng-Chart/Axes/Types/categorical.md
  docs/ui/ng-components/ng-Chart/Axes/Types/datetimecategorical.md
  docs/ui/ng-components/ng-Chart/Axes/Types/datetimecontinuous.md
  docs/ui/ng-components/ng-Chart/Axes/pan-and-zoom.md
  docs/ui/ng-components/ng-Chart/Axes/styling.md
  docs/ui/ng-components/ng-Chart/getting-started.md
  vuejs-docs/ns-ui/Chart/Axes/Types/categorical.md
  vuejs-docs/ns-ui/Chart/Axes/Types/datetimecategorical.md
  vuejs-docs/ns-ui/Chart/Axes/Types/datetimecontinuous.md
  vuejs-docs/ns-ui/Chart/Axes/negative-values.md
  vuejs-docs/ns-ui/Chart/Axes/pan-and-zoom.md
  vuejs-docs/ns-ui/Chart/Axes/styling.md
  vuejs-docs/ns-ui/Chart/Series/Types/area.md
  vuejs-docs/ns-ui/Chart/Series/Types/bar.md
  vuejs-docs/ns-ui/Chart/Series/Types/bubble.md
  vuejs-docs/ns-ui/Chart/Series/Types/candlestick.md
  vuejs-docs/ns-ui/Chart/Series/Types/donut.md
  vuejs-docs/ns-ui/Chart/Series/Types/line.md
  vuejs-docs/ns-ui/Chart/Series/Types/ohlc.md
  vuejs-docs/ns-ui/Chart/Series/Types/pie.md
  vuejs-docs/ns-ui/Chart/Series/Types/range-bar.md
  vuejs-docs/ns-ui/Chart/Series/Types/scatter-bubble.md
  vuejs-docs/ns-ui/Chart/Series/Types/scatter.md
  vuejs-docs/ns-ui/Chart/Series/Types/spline-area.md
  vuejs-docs/ns-ui/Chart/Series/Types/spline.md
  vuejs-docs/ns-ui/Chart/Series/labels.md
  vuejs-docs/ns-ui/Chart/Series/overview.md
  vuejs-docs/ns-ui/Chart/Series/stack-mode.md
  vuejs-docs/ns-ui/Chart/Series/styling.md
  vuejs-docs/ns-ui/Chart/annotations.md
  vuejs-docs/ns-ui/Chart/getting-started.md
  vuejs-docs/ns-ui/Chart/grid.md
  vuejs-docs/ns-ui/Chart/legend.md
  vuejs-docs/ns-ui/Chart/overview.md
  vuejs-docs/ns-ui/Chart/trackball.md
  vuejs-docs/ns-ui/DataForm/dataform-validation.md
Labels: cla: yes
