Repository NativeScript/docs, pull requests merged in 2020-02, with the labels that each got.

#1865 docs: Document metadata filtering
  docs/core-concepts/android-runtime/metadata/overview.md
  docs/core-concepts/ios-runtime/Overview.md
  docs/core-concepts/metadata.md
  docs/core-concepts/project-structure-app.md
  docs/plugins/plugin-reference.md
Labels: cla: yes

#1867 feat: add docs for setting custom webpack configuration file
  docs/core-concepts/project-structure-app.md
  docs/tooling/custom-webpack-cofiguration.md
Labels: cla: yes

#1868 feat: add docs for supported package managers
  docs/tooling/custom-webpack-configuration.md
  docs/tooling/package-managers.md
Labels: cla: yes

#1869 docs: Add empty line before numbered list
  docs/plugins/Use-Native-iOS-Libraries.md
Labels: cla: yes, docs

#1872 fix: Broken "Improve this article" links
  build/_config.yml
Labels: bug, cla: yes

#1870 fix: broken links
  docs/core-concepts/angular-navigation.md
  docs/performance-optimizations/lazy-loading.md
  docs/tooling/debugging/chrome-devtools.md
  docs/ui/overview.md
Labels: cla: yes

#1874 fix: remove temporary redirects (302) and make them permanent (301)
  build/nginx.conf
Labels: cla: yes

#1873 fix: missing closing </code> tag
  docs/start/ns-setup-os-x.md
Labels: cla: yes
